#
# This file is part of Barista.
# Copyright (C) 2007-2011 Xavier Clerc.
#
# Barista is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Barista is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

default: compile run diff clean

ifeq ($(COVERAGE),)
LIBRARIES=$(patsubst %,%.$(LIB_EXT),bigarray camomile unix zip str baristaLibrary)
INCLUDES=-I ../../_build -I +zip
else
LIBRARIES=$(patsubst %,%.$(LIB_EXT),bisect bigarray camomile unix zip str baristaLibrary)
INCLUDES=-I ../../_build -I +zip -I +bisect
endif

compile: FORCE
	@$(COMP) $(FLAGS) $(INCLUDES) $(LIBRARIES) source.ml -o prog.$(PROG_EXT)

run: FORCE
	@$(RUN_PROG) ./prog.$(PROG_EXT) > result

diff: FORCE
	@diff -q result reference

clean: FORCE
	@rm -f *.cm* *.o *.jo ./prog.$(PROG_EXT)
	@rm result

FORCE:
